version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - FLASK_DEBUG=0
      # Optional: set OPENAI_API_KEY to enable LLM keyword extraction
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
    volumes:
      - ./data:/app/data
    networks:
      - rex_net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - rex_net

networks:
  rex_net:
    driver: bridge
